### ISSUE TITLE
Empty screen \ Student can view admin layout

### ISSUE THREAD

**Issue by oisaryk** [IF-092-UI/final_project#104]
![app_student_login](https://user-images.githubusercontent.com/5487834/50903906-a2419d80-1427-11e9-8b19-3a354a04ca16.png)

![admin_layout](https://user-images.githubusercontent.com/5487834/50904002-dcab3a80-1427-11e9-9735-b8c09d0b1040.png)

**Steps-to-reproduce:** 
1. Start the app on 4200
2. Login with student credentials (btw they are visible, check your tests)
3. Try to press right \ left arrow navigation button.

You can navigate http://localhost:4200/#/shell/admin-panel and check all admin dashboard structure.

**Comment by oisaryk** [comment]
Anyone here ?)

**Comment by Rihovardini** [comment]
Fixed bug with errors and empty screen

**Comment by tarasIV** [comment]
Fixed bug student can view admin layout.
